# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 067394ac77aa664bab2dbc1ae816da241a00323391d668c60dfa9422beddd0a80a53a44948915e741f59752cb5f6cf117f57d2d7ce3a8c49322ec9366ec0a9ab

test:
  secret_key_base: 386e30f96b0a7c6fa5bee74d08c235cf2eed1b7e15d1ab119c010f8f300f2e237944dfbbfc005ad5be9f6046466eb2dad14d8e0f4f447c8c905a5ec355a21e28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
